-- SkinScout — initial schema
--
-- Design principle: every table is tagged, in its own comment block, as one of:
--   [SOURCE]    raw data copied from Open Beauty Facts (OBF). Never hand-edited;
--               re-importing should be able to overwrite these columns safely.
--   [DERIVED]   SkinScout-owned structured data: either computed by our own
--               rule engine from [SOURCE] data, or manually curated by the team
--               (e.g. price, which OBF does not provide at all). Editable by us.
--   [AI]        interpretive content generated by an LLM (scores, verdicts,
--               prose) — versioned and clearly separated so it is never
--               confused with a verified fact.
--   [LOOKUP]    small, mostly-static controlled vocabularies.
--
-- No product/skin-type/concern/price data is assumed to exist in OBF beyond
-- what OBF actually documents (barcode, name, brand, raw category tags,
-- raw ingredients text/list, quantity, images, labels). Everything else in
-- this schema (skin type suitability, concern suitability, texture, price,
-- compatibility, "scores") is explicitly SkinScout-derived or AI-generated.

create extension if not exists pgcrypto; -- gives us gen_random_uuid()

-- Reusable "touch updated_at" trigger, applied to mutable tables below.
create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- =========================================================================
-- LOOKUP TABLES
-- Small, mostly-static controlled vocabularies. Seeded once, rarely change.
-- =========================================================================

-- [LOOKUP] product_categories
-- Purpose: SkinScout's own clean category taxonomy (Cleanser, Serum, ...),
-- decoupled from OBF's messy free-form category tags. products.raw_categories
-- stores what OBF actually said; product_attributes.category_id stores which
-- one of THESE canonical categories we mapped it to.
create table product_categories (
  id          uuid primary key default gen_random_uuid(),
  key         text not null unique,           -- e.g. 'cleanser'
  label       text not null,                   -- e.g. 'Cleanser'
  sort_order  smallint not null default 0,
  created_at  timestamptz not null default now()
);

-- [LOOKUP] skin_types
-- Purpose: controlled vocabulary for skin types a product can suit.
-- Matches the frontend's SKIN_TYPES list (Dry, Oily, Combination, Sensitive, Normal).
create table skin_types (
  id     uuid primary key default gen_random_uuid(),
  key    text not null unique,                 -- e.g. 'dry'
  label  text not null                          -- e.g. 'Dry'
);

-- [LOOKUP] concerns
-- Purpose: controlled vocabulary for skincare concerns.
-- Matches the frontend's CONCERNS list (Acne, Dehydration, Pigmentation, ...).
create table concerns (
  id     uuid primary key default gen_random_uuid(),
  key    text not null unique,                 -- e.g. 'acne'
  label  text not null                          -- e.g. 'Acne'
);

-- [LOOKUP] cosmetic_functions
-- Purpose: controlled vocabulary of what an ingredient DOES cosmetically
-- (hydrating, exfoliating, brightening, preservative, fragrance, ...).
-- This is the vocabulary that ingredient_functions (below) links ingredients to.
create table cosmetic_functions (
  id           uuid primary key default gen_random_uuid(),
  key          text not null unique,            -- e.g. 'hydrating'
  label        text not null,                    -- e.g. 'Hydrating'
  description  text
);

-- =========================================================================
-- CORE CATALOG — [SOURCE]-heavy tables, populated from Open Beauty Facts
-- =========================================================================

-- [SOURCE] brands
-- Purpose: canonical brand list. Bootstrapped from OBF's free-form "brands"
-- string field, deduplicated by us (OBF gives no stable brand ID).
create table brands (
  id               uuid primary key default gen_random_uuid(),
  name             text not null,                 -- display name, e.g. "CeraVe"
  normalized_name  text not null,                  -- lowercased/trimmed, for de-duping OBF's free-text brand strings
  source           text not null default 'open_beauty_facts'
                     check (source in ('open_beauty_facts', 'manual')),
  created_at       timestamptz not null default now(),
  constraint brands_normalized_name_key unique (normalized_name)
);

-- [SOURCE] products
-- Purpose: one row per physical product, keyed by OBF barcode when we have one.
-- Columns here are what OBF actually documents. Nothing about skin type,
-- concern, texture, price or "scores" lives on this table — see
-- product_attributes / product_ai_profiles for that.
create table products (
  id                   uuid primary key default gen_random_uuid(),
  obf_barcode          text,                          -- OBF "code" field; null for non-OBF/manual entries (e.g. today's 12 demo products)
  name                 text not null,                 -- OBF "product_name"
  brand_id             uuid references brands(id) on delete set null,
  generic_name         text,                           -- OBF "generic_name", nullable — often missing
  quantity_raw         text,                           -- OBF "quantity" as a free-text string, e.g. "150 ml" — NOT a parsed number
  image_url            text,
  raw_categories_text  text,                           -- OBF "categories" field verbatim, e.g. "en:facial-cleansers,en:cosmetics"
  raw_ingredients_text text,                           -- OBF "ingredients_text" verbatim, before we parse it into product_ingredients
  raw_labels_text      text,                           -- OBF "labels" field verbatim, e.g. "en:vegan,en:cruelty-free-and-vegan"
  countries_text       text,                           -- OBF "countries" field verbatim
  lang                 text,                           -- OBF "lang" field (ingredient/label language)
  source               text not null default 'open_beauty_facts'
                         check (source in ('open_beauty_facts', 'manual')),
  obf_last_modified_at timestamptz,                    -- OBF's own last-edited timestamp, for detecting re-import changes
  imported_at          timestamptz,                    -- when WE last imported/refreshed this row from OBF
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now(),
  constraint products_obf_barcode_key unique (obf_barcode)
);
create index products_brand_id_idx on products (brand_id);
create index products_name_idx on products (lower(name));
create trigger products_set_updated_at
  before update on products
  for each row execute function set_updated_at();

-- [SOURCE] ingredients
-- Purpose: canonical ingredient dictionary. Bootstrapped from OBF's parsed
-- ingredient tags/INCI names, deduplicated by us. This is the "dictionary";
-- product_ingredients (below) is what links a specific product to these.
create table ingredients (
  id               uuid primary key default gen_random_uuid(),
  canonical_name   text not null,                 -- our normalized display name, e.g. "Niacinamide"
  inci_name        text,                           -- INCI name if known, e.g. "Niacinamide"
  obf_tag          text,                           -- OBF ingredient taxonomy tag if matched, e.g. "en:niacinamide"
  source           text not null default 'open_beauty_facts'
                     check (source in ('open_beauty_facts', 'manual')),
  created_at       timestamptz not null default now(),
  constraint ingredients_canonical_name_key unique (canonical_name)
);
create index ingredients_obf_tag_idx on ingredients (obf_tag);

-- [SOURCE] product_ingredients
-- Purpose: links a product to its ingredients IN ORDER (INCI lists are
-- ordered by descending concentration — position matters). Parsed from
-- products.raw_ingredients_text; percent_estimate is OBF's own estimate
-- when it provides one (often null — OBF rarely knows exact percentages).
create table product_ingredients (
  product_id       uuid not null references products(id) on delete cascade,
  ingredient_id     uuid not null references ingredients(id) on delete restrict,
  position          smallint not null,             -- 1 = first-listed/highest concentration
  raw_text_fragment text,                           -- the exact substring from raw_ingredients_text this was parsed from, for auditability
  percent_estimate  numeric(5,2),                   -- OBF's estimated %, when present; nullable — most rows will not have this
  is_allergen       boolean not null default false, -- from OBF's "may contain" / allergen tagging, when available
  primary key (product_id, position),
  constraint product_ingredients_unique_pair unique (product_id, ingredient_id)
);
create index product_ingredients_ingredient_id_idx on product_ingredients (ingredient_id);

-- =========================================================================
-- DERIVED — SkinScout-owned structured data (rule-computed or hand-curated)
-- =========================================================================

-- [DERIVED] product_attributes
-- Purpose: one-to-one "our take" row per product for single-valued fields
-- that OBF does not provide at all. price_eur, texture and category_id are
-- currently manually curated by the team. rule_version and computed_at
-- record which run of our logic last touched this row so re-runs are
-- auditable.
--
-- fragrance_free is intentionally a three-state field backed by an explicit
-- evidence basis, NOT a plain boolean inferred from absence of evidence:
--   fragrance_free = true  + basis = 'label_claim'        → OBF/manufacturer
--                                                            explicitly labels
--                                                            it fragrance-free
--   fragrance_free = false + basis = 'ingredient_detected' → a fragrance/
--                                                            parfum ingredient
--                                                            was found in the
--                                                            parsed list
--   fragrance_free = null  + basis = 'unknown'             → no positive claim
--                                                            AND no fragrance
--                                                            ingredient found —
--                                                            this is NOT proof
--                                                            of fragrance-free,
--                                                            just insufficient
--                                                            evidence either way
-- The CHECK constraint below makes it impossible to store "true" from mere
-- absence of a fragrance ingredient — true requires an explicit label claim.
create table product_attributes (
  product_id           uuid primary key references products(id) on delete cascade,
  category_id          uuid references product_categories(id) on delete set null,
  texture               text,                            -- e.g. 'Gel', 'Cream', 'Lightweight lotion' — manually curated, free text for now
  price_eur             numeric(8,2),                     -- NOT in OBF at all; manually entered by the team until we have a pricing source
  size_ml                numeric(8,2),                      -- parsed/confirmed from quantity_raw where possible; manually corrected otherwise
  fragrance_free         boolean,                           -- three-state: true / false / null — see comment above; never default to a value
  fragrance_free_basis   text not null default 'unknown'
                           check (fragrance_free_basis in ('label_claim', 'ingredient_detected', 'unknown')),
  attribute_source text not null default 'manual'
                     check (attribute_source in ('manual', 'rule')),
  rule_version     text,                              -- which version of our derivation logic produced this row, when attribute_source = 'rule'
  computed_at      timestamptz,
  updated_at       timestamptz not null default now(),
  constraint product_attributes_fragrance_free_evidence check (
    (fragrance_free is true  and fragrance_free_basis = 'label_claim') or
    (fragrance_free is false and fragrance_free_basis = 'ingredient_detected') or
    (fragrance_free is null  and fragrance_free_basis = 'unknown')
  )
);
create trigger product_attributes_set_updated_at
  before update on product_attributes
  for each row execute function set_updated_at();
comment on column product_attributes.fragrance_free is
  'Three-state evidence-backed flag. true requires an explicit fragrance-free label claim (basis=label_claim); false requires a detected fragrance/parfum ingredient (basis=ingredient_detected); null means insufficient evidence either way (basis=unknown). Absence of a fragrance ingredient alone must NEVER set this to true — enforced by product_attributes_fragrance_free_evidence.';

-- [DERIVED] product_skin_type_fit
-- Purpose: many-to-many — which skin types a product suits, and how well.
-- fit_score is OUR estimate (rule-based, later possibly AI-assisted), never
-- a claim from OBF.
create table product_skin_type_fit (
  product_id    uuid not null references products(id) on delete cascade,
  skin_type_id  uuid not null references skin_types(id) on delete restrict,
  fit_score     smallint check (fit_score between 0 and 100),
  source        text not null default 'manual' check (source in ('manual', 'rule')),
  primary key (product_id, skin_type_id)
);
create index product_skin_type_fit_skin_type_id_idx on product_skin_type_fit (skin_type_id);

-- [DERIVED] product_concern_fit
-- Purpose: many-to-many — which skincare concerns a product addresses, and
-- how well. Same provenance rules as product_skin_type_fit.
create table product_concern_fit (
  product_id  uuid not null references products(id) on delete cascade,
  concern_id  uuid not null references concerns(id) on delete restrict,
  fit_score   smallint check (fit_score between 0 and 100),
  source      text not null default 'manual' check (source in ('manual', 'rule')),
  primary key (product_id, concern_id)
);
create index product_concern_fit_concern_id_idx on product_concern_fit (concern_id);

-- [DERIVED] ingredient_functions
-- Purpose: many-to-many — what each ingredient DOES (see cosmetic_functions
-- lookup above). This is the knowledge base our rule engine reads to compute
-- product_skin_type_fit / product_concern_fit from a product's ingredient
-- list, instead of guessing per-product. Curated by the team; not from OBF.
create table ingredient_functions (
  ingredient_id  uuid not null references ingredients(id) on delete cascade,
  function_id    uuid not null references cosmetic_functions(id) on delete restrict,
  weight         smallint not null default 1 check (weight between 1 and 5), -- how strongly this ingredient exhibits this function
  source         text not null default 'manual' check (source in ('manual', 'ai_suggested')),
  reviewed_by_human boolean not null default false, -- must be true before a rule run trusts an 'ai_suggested' row
  notes          text,
  primary key (ingredient_id, function_id)
);
create index ingredient_functions_function_id_idx on ingredient_functions (function_id);

-- [DERIVED/AI] compatibility_rules
-- Purpose: ingredient-pair interaction rules (e.g. "don't layer retinal and
-- vitamin C same session"). Generalized at the INGREDIENT level rather than
-- product level so one rule covers every product containing that pair.
-- Can originate from our own curation or an AI suggestion, but an
-- 'ai_suggested' row must be reviewed_by_human before it's used to warn users.
create table compatibility_rules (
  id                 uuid primary key default gen_random_uuid(),
  ingredient_a_id    uuid not null references ingredients(id) on delete cascade,
  ingredient_b_id    uuid not null references ingredients(id) on delete cascade,
  relationship       text not null check (relationship in ('caution', 'avoid', 'synergy')),
  reason             text not null,
  source             text not null default 'manual' check (source in ('manual', 'ai_suggested')),
  reviewed_by_human  boolean not null default false,
  created_at         timestamptz not null default now(),
  constraint compatibility_rules_distinct_ingredients check (ingredient_a_id <> ingredient_b_id),
  constraint compatibility_rules_ordered_pair check (ingredient_a_id < ingredient_b_id), -- enforces a canonical order so (A,B) and (B,A) can't both be inserted
  constraint compatibility_rules_unique_pair unique (ingredient_a_id, ingredient_b_id)
);
create index compatibility_rules_ingredient_b_id_idx on compatibility_rules (ingredient_b_id);

-- =========================================================================
-- AI — interpretive content generated by an LLM, explicitly versioned
-- =========================================================================

-- [AI] product_ai_profiles
-- Purpose: the AI-authored "scouting" layer — scores, verdict prose,
-- strengths/weaknesses, usage notes. Mirrors the STAT_META keys used by the
-- current frontend (hydration, acne, sensitivity, brightening, antiAgeing,
-- ingredientQuality, value) as explicit smallint columns rather than JSON,
-- so they stay queryable/sortable. Versioned via is_current + generated_at
-- so we can regenerate without destroying prior output, and so nothing here
-- is ever mistaken for a verified fact.
--
-- *** DISPLAY / EXPERIMENTATION ONLY ***
-- The deterministic recommendation/ranking engine MUST NOT read this table.
-- These 0-100 scores are LLM-generated interpretation, not verifiable facts,
-- and are not reproducible or explainable in the way a ranking algorithm
-- needs. Deterministic ranking must be built from the [DERIVED] rule-based
-- signals instead: product_skin_type_fit, product_concern_fit,
-- ingredient_functions and compatibility_rules — each of those rows carries
-- a `source` ('manual' or 'rule') and is traceable back to specific
-- ingredients, which is what "explainable" requires. AI scores may still be
-- shown in the UI (e.g. the ScorePill/radar chart) as a separate, clearly
-- labelled layer, but they are never an input to a ranking decision.
create table product_ai_profiles (
  id                  uuid primary key default gen_random_uuid(),
  product_id          uuid not null references products(id) on delete cascade,
  is_current          boolean not null default true,
  rating              smallint check (rating between 0 and 100),         -- overall score shown as the big ScorePill
  stat_hydration          smallint check (stat_hydration between 0 and 100),
  stat_acne               smallint check (stat_acne between 0 and 100),
  stat_sensitivity        smallint check (stat_sensitivity between 0 and 100),
  stat_brightening        smallint check (stat_brightening between 0 and 100),
  stat_anti_ageing        smallint check (stat_anti_ageing between 0 and 100),
  stat_ingredient_quality smallint check (stat_ingredient_quality between 0 and 100),
  stat_value              smallint check (stat_value between 0 and 100),
  verdict             text,               -- one-line editorial summary, e.g. "The reliable veteran..."
  strengths           text[],
  weaknesses          text[],
  best_for            text[],
  usage_notes         text,
  model_name          text not null,       -- e.g. 'claude-sonnet-4-6'
  prompt_version      text not null,       -- our own version tag for the prompt template used
  generated_at        timestamptz not null default now(),
  reviewed_by_human   boolean not null default false
);
create index product_ai_profiles_product_id_idx on product_ai_profiles (product_id);
-- Only one "current" AI profile per product at a time:
create unique index product_ai_profiles_one_current_per_product
  on product_ai_profiles (product_id)
  where is_current;

comment on table product_ai_profiles is
  'AI-generated interpretive content — DISPLAY/EXPERIMENTATION ONLY. The deterministic recommendation/ranking engine MUST NOT read this table or any stat_* / rating column from it. Use product_skin_type_fit, product_concern_fit, ingredient_functions and compatibility_rules for ranking — they are explainable and traceable to specific ingredients.';
comment on column product_ai_profiles.rating is 'LLM-generated overall score for display only. Not a ranking signal.';
comment on column product_ai_profiles.stat_hydration is 'LLM-generated score for display only. Not a ranking signal — see product_concern_fit.';
comment on column product_ai_profiles.stat_acne is 'LLM-generated score for display only. Not a ranking signal — see product_concern_fit.';
comment on column product_ai_profiles.stat_sensitivity is 'LLM-generated score for display only. Not a ranking signal — see product_skin_type_fit.';
comment on column product_ai_profiles.stat_brightening is 'LLM-generated score for display only. Not a ranking signal — see product_concern_fit.';
comment on column product_ai_profiles.stat_anti_ageing is 'LLM-generated score for display only. Not a ranking signal — see product_concern_fit.';
comment on column product_ai_profiles.stat_ingredient_quality is 'LLM-generated score for display only. Not a ranking signal.';
comment on column product_ai_profiles.stat_value is 'LLM-generated score for display only. Not a ranking signal.';

comment on table product_skin_type_fit is 'Rule/manual-derived, explainable fit signal. This — not product_ai_profiles — is the correct input for deterministic skin-type ranking.';
comment on table product_concern_fit is 'Rule/manual-derived, explainable fit signal. This — not product_ai_profiles — is the correct input for deterministic concern-based ranking.';

-- =========================================================================
-- ROW LEVEL SECURITY
-- Everything above is public catalog data (no user accounts/PII yet), so we
-- enable RLS on every table and allow anonymous read-only access. There is
-- deliberately no INSERT/UPDATE/DELETE policy yet — writes happen only via
-- the service-role key (import scripts, admin tooling), never from the browser.
-- =========================================================================

do $$
declare
  t text;
begin
  for t in select unnest(array[
    'brands', 'product_categories', 'skin_types', 'concerns', 'cosmetic_functions',
    'products', 'ingredients', 'product_ingredients',
    'product_attributes', 'product_skin_type_fit', 'product_concern_fit',
    'ingredient_functions', 'compatibility_rules', 'product_ai_profiles'
  ])
  loop
    execute format('alter table %I enable row level security;', t);
    execute format(
      'create policy %I on %I for select using (true);',
      t || '_public_read', t
    );
  end loop;
end $$;
